### PR TITLE
ProfileFile: Corrects behaviour when config and credentials not found

### PR DESCRIPTION
**Pull request by martinKindall**
Now it returns an empty map, as it used to in previous sdk versions.

## Motivation and Context
https://github.com/aws/aws-sdk-java-v2/issues/3869

## Modifications
Returning empty map instead of null. This prevents null-pointer exceptions when calling the profiles() method.

## Testing
The included tests were tested running the unit tests of that module with ./mvnw package
Testing environment

Java version: 1.8.0_361, vendor: Oracle Corporation
OS name: "windows 10", version: "10.0", arch: "amd64"

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by debora-ito** [comment]
@martinKindall thank you for the PR.

To make the changelog entry you need to run the `scripts/new-change` script and follow the instructions, then commit the new file created by the script in `.changes/next-release`.

You can review our CONTRIBUTING guide [here](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) to make sure you've checked all guidelines.

**Comment by martinKindall** [comment]
> To make the changelog entry you need to run the `scripts/new-change` script and follow the instructions, then commit the new file created by the script in `.changes/next-release`.

Ok, now I added the changelog changes according to the script.

**Review by millems — APPROVED** [review]

**Comment by martinKindall** [comment]
Some pipelines are failing but seems like not because of the changes, but rather the action `aws-actions/configure-aws-credentials@v1` is missing credentials. Is there something I can do?

**Comment by debora-ito** [comment]
Only the builds marked as required are necessary. One of those failed though, I'll retry.

**Pull request merged**
