### PR TITLE
Use virtual style addressing for non Amazon S3 endpoints.

### PR DESCRIPTION
**Pull request by ebabani**
## Description
Allow using the dns style (bucket.s3-endpoint) instead or forcing the path style (s3-endpoint/bucket) for non Amazon s3-compatible endpoint. This allows using the sdk with third party providers that only support the dns style for access (eg. Alicloud)

## Motivation and Context

Allows using this sdk with any third party s3 providers that support virtual style addressing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG** 

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by ebabani** [comment]
Related issue: https://github.com/aws/aws-sdk-java-v2/issues/722

**Comment by ebabani** [comment]
@millems Could I get someone to take a look at this PR?

The travis failure seems unrelated, and I don't know if I have a way to re-run the test.

**Comment by millems** [comment]
Sorry, talking with the others on our end, it looks like we've actually standardized this behavior across the latest SDK versions:
> Determining which addressing style to use:
>
> In general, SDK's MUST default to using virtual hosted-style addressing when making S3 API calls that address an S3 bucket. However, SDK's MUST default to path style addressing under the following scenarios:
> 
> * The S3 bucket being addressed is non-DNS compatible. To determine DNS compatibility of a bucket, read the section on DNS compatibility.
> 
> * The S3 bucket being addressed has one or more periods (.) in its name. If the request is being sent over HTTP instead of HTTPS, SDK's MAY chose to default to virtual hosted-style addressing despite the period in the bucket name.
> 
> * The client is explicitly configured to use path style addressing and the request being sent is not to an S3 accelerate endpoint. For more information related to configuration, read the section on client configuration.

You can explicitly disable path-style addressing in the S3 client builder:

```Java
S3Client.builder()
        .serviceConfiguration(c -> c.pathStyleAccessEnabled(true))
        .build();
```

... but in the interest of behavioral parity with the other SDKs, we won't be able to accept this PR.

**Comment by ebabani** [comment]
@millems Totally agree with that behaviour, but at the moment this SDK is NOT using virtual hosted-style addressing for third party endpoints, and there is no way to change that.

https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java#L141

This PR addresses that limitation, but does not affect the addressing behaviour above.

**Comment by millems** [comment]
It looks like setting path-style access to enabled should work for third-party endpoints: https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java#L63-L69

Is that not the case?

**Comment by ebabani** [comment]
No, the `changeToDnsEndpoint` function has a check that the endpoint must start with `s3`, otherwise it doesn't make the change.

https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java#L141
```
if (mutableRequest.host().startsWith("s3")) {
```

**Comment by millems** [comment]
Ah, I misunderstood the request. For some reason I was thinking it was to use path-style addressing, not virtual style addressing. Reopening. I suppose it could be nice to be able to force virtual-style addressing on. We'll need to talk about whether we want to support this, since it will probably need to be a configuration option, not an implicit behavior.

**Comment by millems** [comment]
Just commenting to thank you for your patience on this issue. I know we haven't replied in a while. I'm a little nervous about merging this as-is, because it could break people who need path-style for third-party services and are relying on the current behavior.

**Comment by ebabani** [comment]
No worries, I'm good with closing this PR since it's difficult to change the default behaviour.  I was able to use a fork for my purposes.

**Pull request closed without merging**
