### PR TITLE
add 'oraclejdk10' to Travis build matrix

### PR DESCRIPTION
**Pull request by sullis**
## Description

add 'oraclejdk10' to Travis build matrix

## Motivation and Context

add 'oraclejdk10' to Travis build matrix

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by sullis** [comment]
Travis CI build failed.

"java.lang.NoClassDefFoundError: javax/annotation/Generated"

**Comment by sullis** [comment]
similar issue:  https://github.com/google/auto/issues/560

**Comment by sullis** [comment]
similar issue:  https://github.com/google/dagger/issues/880

**Comment by sullis** [comment]
Oops.  ' javax.annotation.processing.Generated' was introduced in JDK 9.  It doesn't exist in JDK 8.

**Comment by zoewangg** [comment]
Thanks for the PR. Instead of adding extra loads on Travis, we have created Codebuild jobs to build with JDK9 and JDK10.

Side note, we fixed the `NoClassDefFoundError` issue by avoiding using `javax.annotation.Generated` and using our own `@Generated` annotation instead. See also #584

**Pull request closed without merging**
