### PR TITLE
Delete all DDB mapper related classes

### PR DESCRIPTION
**Pull request by dagnir**

### CODE REVIEW

**Comment by kiiadi** [comment]
Weren't we going to keep these because the integration tests were valuable but move them to some test utility (for now) ?

**Comment by dagnir** [comment]
@kiiadi Okay, I wasn't sure what'd we'd settled on. Not sure what you mean by test utility though. Test package?

**Comment by kiiadi** [comment]
i mean a test module

**Comment by dagnir** [comment]
@kiiadi Cool will do.

**Comment by dagnir** [comment]
Replaced by #108

**Pull request closed without merging**
