### PR TITLE
Fix IamPolicy code example docs.

### PR DESCRIPTION
**Pull request by ManishDait**
## Motivation and Context

The second code snippet in `the IamPolicy` docs contains an error as discuss in issue provide below. i.e 
The eighth line of the snippet:
Does not work because `getPolicyVersionResponse.policyVersion().document()`  returns a URL-encoded string. 

### Issue
https://github.com/aws/aws-sdk-java-v2/issues/4229

## Modifications

Change line eighth of snippet from:
`getPolicyVersionResponse.policyVersion().document()` to

```
String decodedPolicy = URLDecoder.decode(getPolicyVersionResponse.policyVersion().document(), StandardCharsets.UTF_8);
            IamPolicy policy = IamPolicy.fromJson(decodedPolicy);
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [X] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by debora-ito** [comment]
@ManishDait can you confirm that this pull request can be released under the Apache 2 license?

**Comment by ManishDait** [comment]
> @ManishDait can you confirm that this pull request can be released under the Apache 2 license?

Reply

**Comment by ManishDait** [comment]
> @ManishDait can you confirm that this pull request can be released under the Apache 2 license?

Done.

**Review by debora-ito — APPROVED** [review]

**Comment by debora-ito** [comment]
@all-contributors please add @ManishDait for documentation

**Pull request merged**
