### PR TITLE
Fix TCK tests not being run

### PR DESCRIPTION
**Pull request by dagnir**
## Description
At some point looks like the TCK tests stopped getting run as part of the normal
`mvn install` invocation.

## Motivation and Context
Make tests run again.

## Testing

`mvn clean install -pl :netty-nio-client -am` and ensure the TCK tests are run. Same for `sdk-core`. As an additional check, break the tests and ensure the build fails.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [ ] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by dagnir** [comment]
I think one of the tests is currently broken. I'll update with a fix.

**Comment by dagnir** [comment]
Oh there are some tests in `core` as well. I'll update that POM too.

**Comment by zoewangg** [comment]
Wow, TCK tests increased our test coverage by 0.5%!

**Comment by dagnir** [comment]
@zoewangg 🎆

**Pull request merged**
