### PR TITLE
using jackson versions managed by com.fasterxml.jackson:jackson-bom

### PR DESCRIPTION
**Pull request by tomliu4uber**
## Description

import Jackson dependency management from `com.fasterxml.jackson:jackson-bom`, instead of managing Jackson dependencies component by component

## Motivation and Context

fix the mismatched `jackson-annotation` version

https://github.com/aws/aws-sdk-java-v2/issues/948

## Testing

recompile the whole project and make sure all unit tests pass

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [X ] I have read the **CONTRIBUTING** document
- [ ] Local run of `mvn install` succeeds
- [X ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ X] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](../docs/LaunchChangelog.md)

## License

- [ X] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by zoewangg** [comment]
Thank you for the PR! 

From the README file on [jackson-bom repo](https://github.com/FasterXML/jackson-bom), it seems the bom is  intended to be used by only Jackson core components and not the external applications.

We would prefer the second approach you proposed in #948 defining two versions.

**Comment by tomliu4uber** [comment]
I think I messed up the pull request.  I am fixing it

**Comment by zoewangg** [comment]
@tomliu4uber Feel free to close and reopen a new one if that helps : )

**Comment by tomliu4uber** [comment]
here is the new PR: https://github.com/aws/aws-sdk-java-v2/pull/974

**Pull request closed without merging**
