### PR TITLE
Fixed the time marshalling issue when CBOR is disabled. See #1023

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Fixed the time marshalling issue when CBOR is disabled. See #1023 #1021 

## Testing
Added unit tests. Current kinesis integ tests passed.
The  integration tests codebuild job triggered `sqs, dynamodb, s3, kinesis` to run and succeeded(yay!)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](../docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by spfink** [comment]
Thoughts on this solution vs doing the cbor enabled check in the generated service clients?

**Comment by zoewangg** [comment]
I like the idea of doing the cbor check in the generated clients, but customers need to set the `CBOR` property before the client initialization though for it to take effects.

Note that current implementation also doesn't support disabling `CBOR` after client initialization, but we might be able to fix that.

**Comment by zoewangg** [comment]
I should also note that for v1, we support disabling `CBOR` after client initialization.

**Comment by zoewangg** [comment]
Created #1031 to track the issue.

(Integ tests failed because I clicked the `merge branch master`and it was tracking the changes between my commit with master. There was  `pom.xml` change in it and caused the script to fail, the script fix is in another PR)

**Pull request merged**
