### PR TITLE
Update `SslCloseComletionEventHandler`

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Problem: `java.io.IOException: Server failed to send complete response` was thrown incorrectly for error response from the service. See #1076 

The root cause is that there is a race condition between when `ResponseHandler#channelnactive` is triggered and when the response is completed.

The fix is to update `SslCloseComletionEventHandler` to close channel for `SslCloseCompletionEvent` only if the channel is unused. The channel will be closed in `ReponseHandler` afterwards.

See the following stacktrace, by the time the channel was inactive, the response had not been completed yet, so `java.io.IOException: Server failed to send complete response` was thrown.
```
2019-03-05 17:31:02,202 [aws-java-sdk-NettyEventLoop-2-3] READ COMPLETE
2019-03-05 17:31:02,202 [aws-java-sdk-NettyEventLoop-2-3] INFO  software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - onSubscribe being invoked
2019-03-05 17:31:02,205 [aws-java-sdk-NettyEventLoop-2-3] DEBUG INACTIVE
2019-03-05 17:31:02,205 [aws-java-sdk-NettyEventLoop-2-3] INFO  software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - channelInactive being invoked
2019-03-05 17:31:02,205 [aws-java-sdk-NettyEventLoop-2-3] ERROR software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - RESPONSE HAS NOT COMPLETED YET!!!
2019-03-05 17:31:02,215 [aws-java-sdk-NettyEventLoop-2-3] DEBUG CLOSE
2019-03-05 17:31:02,216 [aws-java-sdk-NettyEventLoop-2-3] DEBUG UNREGISTERED
2019-03-05 17:31:02,216 [aws-java-sdk-NettyEventLoop-2-3] INFO  PublisherAdapter.onComplete, Completing the response
2019-03-05 17:31:02,218 [aws-java-sdk-NettyEventLoop-2-3] INFO  software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler - BaosSubscriber.onComplete
``` 

## Testing
Added unit tests and s3 Integ test passed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by zoewangg** [comment]
The channel will be closed in `ResponseHandler` after the response is completed or any exception occurs.

https://github.com/aws/aws-sdk-java-v2/blob/9912da700b70512bd46316cc9bbd9f23f11d0b22/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java#L126-L132

**Comment by zoewangg** [comment]
I guess there might be still some edge cases where the inactive channel is unclosed. We should probably add `channel.close` in `ResponseHandler#channelInactive` to reduce the chance. The requests would fail at the first time but should succeed in retry.

**Comment by spfink** [comment]
Let's definitely test this by using S3 and making requests at low TPS. I don't think this will make the problem as bad as when we didn't have this but I think this increases the likelihood of reusing a bad channel. 

If the testing shows the results are poor, we can always modify the SslCloseCompletionEventHandler to tag the thread or something so that we can make sure not to re-use it later.

**Comment by zoewangg** [comment]
Did some tests with low TPS of s3.getObject and result didn't get worse compared with before.

However, I can still consistently replicate ` java.io.IOException: Server failed to send complete response` issue when the channel sometimes becomes `INACTIVE` right after `READ COMPLETE` without user event `SslCompletionEvent`, which means the service closes the connection without close_notify. There is a race condition between response completing and `ResponseHandler#channelInactive`. I'll address it in another PR

**Comment by zoewangg** [comment]
Found out this does not correctly fix the issue after doing more tests, will create a new PR.

**Comment by zoewangg** [comment]
This change would not make the `fail to complete response` exception worse and will fix the incorrect exception for headBucket. Re-opening.

**Pull request merged**
