### PR TITLE
Build with Java 9+

### PR DESCRIPTION
**Pull request by zoewangg**
Replacing `@javax.annotation.Generated` with our own `@Generated` annotation for better transition.

Unit tests and integration tests succeeded with Java 9 and Java 10.

### CODE REVIEW

**Comment by dagnir** [comment]
Since this will create extra jobs on Travis (adding to the congestion) we should probably add corresponding CodeBuild jobs as well. Similarly we'll gate PR's on those rather than the Travis equivalents. Not saying we should do it as part of this PR though 😄

**Comment by dagnir** [comment]
Hmm would it make sense to build with either 9 or 10 instead of 8 for Travis?

**Comment by zoewangg** [comment]
I'd say we keep it 8 for Travis since v2 is built on top of Java 8.

**Comment by dagnir** [comment]
Makes sense! My thinking was building with 9+ would make it easier for contributors whose builds fail in the CodeBuild 9/10 jobs due to forward compatibility issues. Maybe that'll be a rare case though, and then backwards compat to 8 would be a problem!

**Pull request merged**
