### PR TITLE
Refactored profile-based credential and region loading.

### PR DESCRIPTION
**Pull request by millems**
Code should be simpler and easier to understand. Added support for specifying the region that should be used when calling STS to assume a role when the role is being assumed from a config file.

### CODE REVIEW

**Comment by spfink** [comment]
Does this bring us up to spec with the SEP?

**Comment by millems** [comment]
All of the SEPs (and wikis) that I could find, yes.

**Comment by cornelf** [comment]
would this [issue](https://github.com/aws/aws-sdk-java-v2/issues/197) be addressed here as well?

**Comment by millems** [comment]
I'm not sure! We're going to iterate on this PR a bit more to make it closer to the CLI's behavior. We'll make sure to tackle that issue as well when we're making the changes. Thanks for the report!

**Pull request closed without merging**
