### PR TITLE
InputStream#readAllBytes() should receive no premature EOS

### PR DESCRIPTION
**Pull request by faucct**
A read-call with len == 0 happens here:
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/io/InputStream.java#L396

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Review by mgrundie-r7 — APPROVED** [review]

**Comment by dagnir** [comment]
Thanks @faucct. The change itself looks good; can you please add a test for this here? https://github.com/aws/aws-sdk-java-v2/blob/5aa3ff309ca5698eb452aa077f191d842f0fa55a/utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamSubscriberTest.java#L46

**Comment by faucct** [comment]
I have tried adding the test for it, but don’t know, how to skip its compilation on Java 8. @dagnir , could you add it for me, please, if you know the way?

```
    @EnabledForJreRange(min = JRE.JAVA_9)
    @Test
    public void readAllBytesShouldReceiveNoPrematureEOS() throws IOException {
        publisher.subscribe(subscriber);
        publisher.send(byteBufferOfLength(2 << 14));
        publisher.complete();
        assertThat(subscriber.readAllBytes()).isEqualTo(new byte[2 << 14]);
    }
```

**Comment by dagnir** [comment]
Hey sorry for the delayed response. N worries, I can add a test case.

**Review by dagnir — APPROVED** [review]

**Review by zoewangg — APPROVED** [review]
Can we add a change log entry for this?

**Comment by dagnir** [comment]
@all-contributors please add @faucct for code

**Pull request merged**
