### PR TITLE
Support package name customization

### PR DESCRIPTION
**Pull request by zoewangg**
## Motivation and Context
Allow codegen users to customize package prefix and suffix
- prefix: by default it's `software.amazon.awssdk.services`
- suffix: by default it's the same as service ID, eg: `[packagePrefix].s3`
Example:
```

{
    "packageName": {
        "prefix": "foo.bar",
        "suffix": "helloworld"
    }
}
```

## Testing
Added unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Review by mtdowling — COMMENTED** [review]
Why prefix and suffix and not just a single value to define the package name?

**Comment by zoewangg** [comment]
>Why prefix and suffix and not just a single value to define the package name?

Sure, there are two reasons: 1) this is how v1 is implemented, and I searched internally and there are packages using only one of them, so implementing it the same way may make it easier for users to migrate to v2. 2) supporting a single value is actually more work because it require refactoring of the existing code

**Comment by mtdowling** [comment]
I’m not understanding the difference between prefix and suffix. Do they make up the package name or is suffix the client class name?

If they make up the package name, then I don’t see that as something you should carry forward from v1. To reduce churn in this PR, you could also just parse out the prefix and suffix from a single package name string. Migrating this configuration from v1 to v2 seems like a minimal change and worthwhile since it’s easier to understand for new clients going forward.

**Comment by zoewangg** [comment]
> I’m not understanding the difference between prefix and suffix. Do they make up the package name or is suffix the client class name?

@mtdowling They make up the root package name, `[prefix].[suffix]`. There are subpackages such as `[prefix].[suffix].model`, and `[prefix].[suffix].paginators`. We can add customization for those if needed in the future.

We can't parse out the prefix and suffix because suffix can contain `.` in it.

For example, the following custom config would generate root pacakge `foo.bar.hello.world`
```
{
    "packageName": {
        "prefix": "foo.bar",
        "suffix": "hello.world"
    }
}
```

**Comment by zoewangg** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/4751 is the new PR

**Pull request merged**
