### PR TITLE
Allow StsCredentialsProvider builder to take a ScheduledExecutorService

### PR DESCRIPTION
**Pull request by cloudshiftchris**
Allow StsCredentialsProvider builder to take a ScheduledExecutorService for more efficient background processing.

## Motivation and Context
See #3259.
Reduces the number of threads required for async refresh of credentials.  In multi-tenant setups there can be large numbers of StsCredentialsProvider instances - maintaining a background thread for each one is unnecessary and expensive; this change allows for a shared ScheduledExecutorService to be used to reduce resource consumption.

## Modifications
Provide additional constructors on software.amazon.awssdk.utils.cache.NonBlocking to take a ScheduledExecutorService (instead of creating one).
Modify software.amazon.awssdk.utils.cache.NonBlocking.close() to only cleanup executor service if owned (created) by this instance.
Modify software.amazon.awssdk.services.sts.auth.StsCredentialsProvider to allow a ScheduledExecutorService to be provided via the builder.  When provided, the appropriate NonBlocking constructor is used.

## Testing
Added additional test cases mirroring existing NonBlocking test cases to confirm no change in behaviour.

## Screenshots (if appropriate)
n/a

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [X] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [X] Local run of `mvn install` succeeds
- [X] My code follows the code style of this project
- [X] My change requires a change to the Javadoc documentation
- [X] I have updated the Javadoc documentation accordingly
- [X] I have added tests to cover my changes
- [X] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License
- [X] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by millems** [comment]
Nice contribution! What if the SDK by default shared threads between NonBlocking instances so that you don't have to configure it yourself? Is there a specific reason you want a custom thread pool?

**Comment by cloudshiftchris** [comment]
No specific reason for custom thread pool, other than perhaps configuring
the size based on demand, which could also be done via SDK configuration
(where the SDK was managing a shared pool).

It was the most minimal code change (pass in pool vs creating it); a more
integrated SDK managed one would be great.

Chris.

**Comment by millems** [comment]
Let me take a swing at doing it within the SDK. The main challenge is scheduled executors only working with core threads, and core threads not being reused (even if idle), but we can probably work around that with a couple of executors or something more clever.

 It would be nice if everyone got this improvement, not just people 'in the know'.

**Comment by cloudshiftchris** [comment]
Cool.  I was working around scheduled executor limitations by providing a
larger number of core threads (as it won’t increase pool size).

In looking at the two tiers of timers - scheduled executor task running
every minute that polls cred cache to see if it’s expired - perhaps a
timing wheel or other construct would be more appropriate to handle the
actual timer value.

**Comment by millems** [comment]
Oh yeah, jitter is a good idea, didn't think about that.

**Comment by millems** [comment]
My swing: https://github.com/aws/aws-sdk-java-v2/pull/3275

If it looks good to you, did you want to try it out to make sure you see the resource consumption reduction you expect?

**Comment by cloudshiftchris** [comment]
@millems great work; added a few comments.  Travelling atm (for the remainder of the week), won't be able to directly test, though the resource consumption improvements are evident in the removal of the per-cred-provider executor.

Thanks for tackling this.

**Comment by millems** [comment]
I don't see your feedback on the PR. Did you miss hitting publish, or am I blind?

**Comment by cloudshiftchris** [comment]
S/b a couple of comments on there, let me check…

**Comment by cloudshiftchris** [comment]
Can’t see them atm - afk for a few hours, will drop them in again.

**Pull request closed without merging**
