### PR TITLE
Travis build: add 'oraclejdk9'

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
cc: @millems

**Comment by dagnir** [comment]
@sullis Do you mind removing the changelog entry? We don't need to track build system changes in the CL. Also I think you'll need to change the distribution to `trusty` to make JDK9 available.

**Comment by sullis** [comment]
[ x ] I confirm that this pull request can be released under the Apache 2 license

**Comment by sullis** [comment]
ping @dagnir

**Comment by sullis** [comment]
obsolete.

**Pull request closed without merging**
