### PR TITLE
Added an aggregate changelog for all changes since 1.11.x.

### PR DESCRIPTION
**Pull request by millems**

### CODE REVIEW

**Comment by dagnir** [comment]
Can we add a TOC at the top?

**Comment by millems** [comment]
Done

**Comment by dagnir** [comment]
Oops sorry I missed the table in 1.3 as well:

https://github.com/aws/aws-sdk-java-v2/blob/4a885a5e0c092e1f032610a93d58a3a664e16a51/docs/LaunchChangelog.md#13-sdk-client-configuration

**Comment by millems** [comment]
Oops, me too! Fixed.

**Pull request merged**
