### PR TITLE
Netty 4.1.39.Final

### PR DESCRIPTION
**Pull request by sullis**
## Description

Netty 4.1.36.Final

## Motivation and Context

latest version of Netty

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by spfink** [comment]
Hi @sullis,

Thanks for helping us to keep our dependency versions up to date! However, I'm not sure when we'll get to merging this one. We've had some issues with taking even patch version changes of the Netty client. We've got some work in-progress which will give us additional confidence here.

**Comment by sullis** [comment]
fyi - Netty's lead developer says: "please upgrade as soon as possible"

=> https://twitter.com/normanmaurer/status/1123285837859495937

**Comment by dagnir** [comment]
Per #1344, looks like some HTTP/2 releated `@UnstableApi` classes have changed in 4.1.36.Final.

**Comment by wreulicke** [comment]
fyi: https://twitter.com/normanmaurer/status/1161341497847013377
"If you use #netty to serve #http2 on the internet you should upgrade ASAP."

I would like to upgrade netty, but aws sdk java v2 is blocking...

**Comment by sullis** [comment]
Netty 4.1.39
https://netty.io/news/2019/08/13/4-1-39-Final.html

**Comment by dagnir** [comment]
Closing in favor of #1391.

**Comment by dagnir** [comment]
Hey @sullis I closed this PR since there are some necessary code changes for this upgrade (see #1391).

**Pull request closed without merging**
