### PR TITLE
Netty 4.1.13 -> 4.1.17

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ping @varunnvs92 @kiiadi

**Comment by kiiadi** [comment]
Are you happy to submit this subject to Apache 2.0 license? https://github.com/aws/aws-sdk-java-v2/blob/master/LICENSE.txt

**Comment by sullis** [comment]
yes.

**Comment by sullis** [comment]
[ x ] I confirm that this pull request can be released under the Apache 2 license

**Pull request merged**
