### PR TITLE
Make sure each module has a dedicated package root.

### PR DESCRIPTION
**Pull request by zoewangg**
Make sure each module has a dedicated package root.

If a service is sharing models with other service, the package root of that service is going to be within that shared service package.
eg:

dynamodb -> `software.amazon.awssdk.services.dynamodb`
dynamodbstreams -> `software.amazon.awssdk.services.dynamodb.dynamodbstreams`

waf -> `software.amazon.awssdk.services.waf`
waf-regional: -> `software.amazon.awssdk.services.waf.wafregional`

### CODE REVIEW

**Comment by shorea** [comment]
What do the shared models look like with this?

**Comment by zoewangg** [comment]
the models and shared unmarshaller/marshallers are still in the top level service package, `software.amazon.awssdk.services.dynamodb.model` in this case.

screen shot 2018-07-05 at 3 47 06 pm

**Comment by shorea** [comment]
Is there a way to customize the package name so it's not so wordy? I'd rather see software.amazon.awssdk.services.dynamodb.streams

**Comment by zoewangg** [comment]
Added customization for package name.

Here's how the new package look like:
dynamodbstreams -> `software.amazon.awssdk.services.dynamodb.streams`
waf-regional: -> `software.amazon.awssdk.services.waf.regional`

**Pull request merged**
