### PR TITLE
Set tableSchema to chained extensions read context

### PR DESCRIPTION
**Pull request by alvinsee**
## Motivation and Context
DynamoDB Enhanced Client allows custom extensions to be installed. However, the behavior of the meta extension ChainExtension differs when providing a `DefaultDynamoDbExtensionContext` to each extension's invocation of `afterRead`. The [default behavior](https://github.com/aws/aws-sdk-java-v2/blob/620c4c5690d5109a26940262d988ddb35cf7ecc1/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java#L78) for a single extension (by ways of `VersionRecordExtension`) passes in the table schema to the builder. However, when two or more extensions are specified, `ChainExtension` omits the table schema entirely when it does the delegation. This breaks any custom extension that might require inferring the table schema in a read operation.

## Description
- sets `tableSchema` field when provisioning the extension context in `ChainExtension#afterRead`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [ ] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Review by HadeelElbitar — APPROVED** [review]

**Review by zoewangg — COMMENTED** [review]
Thank you for submitting the PR. LGTM. Could you add a changelog entry? You can do so by running the scripts/new-change script, following the instructions and then committing the new file created by the script in .changes/next-release with your changes.

**Comment by alvinsee** [comment]
> Thank you for submitting the PR. LGTM. Could you add a changelog entry? You can do so by running the scripts/new-change script, following the instructions and then committing the new file created by the script in .changes/next-release with your changes.

Pushed up the requested change @zoewangg. Thanks!

**Review by zoewangg — APPROVED** [review]
Thank you for your contribution!

**Comment by zoewangg** [comment]
@all-contributors please add @alvinsee for code

**Pull request merged**
