### PR TITLE
Remove JsonPath dependency from sfn module

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Remove jsonPath dependency from sfn module, which has also been done in v1.

## Motivation and Context
removing another non-modularized dependency

## Testing
`mvn clean install`

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by shorea** [comment]
:( do we need to do this?

**Comment by zoewangg** [comment]
Yeah, unfortunately, they are not modularized. Looking at their commit history, it doesn't seem like it's actively maintained. :( https://github.com/json-path/JsonPath/commits/master We can try to open a PR to add automatic-module-name to their repo, but I don't think it will get merged any time soon.

**Comment by shorea** [comment]
Is it possible to shade it?

**Comment by zoewangg** [comment]
We'd still need to add something like `require jsonpath;` to our module-info file as the following and if the module name for json path ever changes, it will break the customers.

https://github.com/aws/aws-sdk-java-v2/blob/1deb48527d130ab0312e57ce3c5061ad199f0aab/codegen/src/main/resources/templates/common/module-info.ftl#L7

**Comment by shorea** [comment]
Why do we need it in our module info if we are shading it?

**Comment by zoewangg** [comment]
As long as we import the jsonpath packages,
```
import com.jayway.jsonpath.InvalidPathException;
import com.jayway.jsonpath.JsonPath;
```
we need to add them to the module info. 

I tried to create a new module, named `thirdparty` to shade the json-path and relocating it to `software.amazon.awssdk.thirdparty.com.jayway.jsonpath`. Then I made sfn depends on `thirdparty` module and changed the package imports to 
`import software.amazon.awssdk.thirdparty.com.jayway.jsonpath.InvalidPathException;`.

This still doesn't work. `thirdparty` will not be able to export the shaded jsonpath pacakge from its `module-info` because it doesn't know the relocated package at compiler time.

```
module thirdparty {
    exports software.amazon.awssdk.thirdparty.com.jayway.jsonpath.InvalidPathException;
} 
```

There might be some other things we can try, but I don't think we can go full modularization with unmodularized dependencies.

**Comment by zoewangg** [comment]
Yeah, shade is is bound to the package phase and we would get compiler error in `module-info.java` `exports software.amazon.awssdk.sfn.thirdparty.com.jayway.jsonpath.InvalidPathException`  because it doesn't know the relocated path at compile time.

**Comment by zoewangg** [comment]
Correction: if we shade it within `sfn` module, we would get compiler error at `import software.amazon.awssdk.sfn.thirdparty.com.jayway.jsonpath.InvalidPathException` and not from the module-info class because we would not export it.

**Comment by zoewangg** [comment]
I think we still need this because removing `jsonpath` later after GA would be considered backwards incompatible. We can add `jsonpath` in the future if it has `Automatic-Module-Name` added.

**Comment by zoewangg** [comment]
Closing in favor of https://github.com/aws/aws-sdk-java-v2/pull/815

**Pull request closed without merging**
