### PR TITLE
Add reflect-config.json to s3-transfer-manager

### PR DESCRIPTION
**Pull request by klopfdreh**
## Motivation and Context
Fixes https://github.com/aws/aws-sdk-java-v2/issues/5127

## Modifications
Added reflect-config.json for ApplyUserAgentInterceptor for s3-transfer-manager module like it is present for ApplyUserAgentInterceptor in dynamodb-enhanced

## Testing
I added a reflect-config.json in my project with the same content like in this PR and performed a native-build with `-H:ReflectionConfigurationResources=META-INF/native-image/reflect-config.json`.

## Screenshots (if appropriate)
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Review by zoewangg — COMMENTED** [review]
LGTM. Could you add a changelog entry? You can just run the `scripts/new-change script` and follow the instructions.

**Comment by klopfdreh** [comment]
Hey @zoewangg -

1. I installed Python 3
2. I changed new-change to `#!/user/bin/env python3`
3. Then I used the following command line: `./new-change --type bugfix --category s3-transfer-manager --contributor klopfdreh --description Added reflect-config.json for ApplyUserAgentInterceptor in s3-transfer-manager for native builds`

Sadly I got this error

```plain
/...../aws-sdk-java-v2/scripts/./new-change:136: SyntaxWarning: invalid escape sequence '\['
  new_description = re.sub('(?<!\[)#\d+', linkify, description)

```

**Comment by zoewangg** [comment]
@klopfdreh could you try running `./new-change` directly following the prompt?

**Comment by klopfdreh** [comment]
Because I didn't use any markdown / links in my comment I commented out the linkify function. I added the newly generated json to the change and force pushed it, so that it is only one commit.

**Comment by klopfdreh** [comment]
> @klopfdreh could you try running `./new-change` directly following the prompt?

I did, but the first line is python2 `#!/usr/bin/env python` which is outdated and should not be used any longer.

**Comment by klopfdreh** [comment]
I removed the duplicated json files in `.changes/next-release` - I hope it is ok now. 😀

**Review by zoewangg — APPROVED** [review]
Thanks for your contribution! Triggering builds

**Comment by zoewangg** [comment]
@all-contributors please add @klopfdreh for code

**Pull request merged**
