### PR TITLE
Change the scm url

### PR DESCRIPTION
**Pull request by jensim**
## Motivation and Context

We use renovate, but it is currently unable to understand where your releases exist, because the `scm.url` points to a place it does not understand. The link is also a dud for clicking.

## Modifications

* update `scm.url`
* add a `scm.connection` because it looked like that was what the previous `scm.url` was trying to point at

## Screenshots (if appropriate)
https://central.sonatype.com/artifact/software.amazon.awssdk/bom/2.20.77
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by debora-ito** [comment]
@jensim  What is `renovate`? Can you give us a reference?

**Review by L-Applin — APPROVED** [review]

**Comment by jensim** [comment]
Thanks for the ✅ @L-Applin 
It seems the workflows wont trigger without an approval, could you or @debora-ito approve this, so we might become green to merge?

**Comment by jensim** [comment]
> I have triggered our CodeBuild test jobs, once they finish all should be good to merge

Cool 😎👍

**Comment by L-Applin** [comment]
merged! Thanks for your contribution 👍

**Comment by jensim** [comment]
> merged! Thanks for your contribution 👍

Cool beans @L-Applin 🌈🦄 It's always fun to make a first contribution, and to receive a warm welcome from the maintainers!
Hope to see you again soon, in another PR ^^
Best Regards

**Pull request merged**
