### PR TITLE
Skip ci build on documentation changes

### PR DESCRIPTION
**Pull request by StephenFlavin**
## Motivation and Context
Changes that only include documentation ~or scripts~ shouldn't cause/require a code build
e.g. [allcontributors](https://github.com/aws/aws-sdk-java-v2/pull/4093) pulls only modify `.all-contributorsrc` and `README.md`

## Modifications
Configures [`paths-ignore`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) in `.github/workflows/codebuild-ci.yml` to skip useless builds

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by debora-ito** [comment]
Successful builds are required for the merge, so I don't think we can skip the build even in those cases.
The change is just to skip the builds, right? What happens if the builds are required?

**Comment by StephenFlavin** [comment]
HI @debora-ito,

With this change the builds won't be required just the Code owner review.
Screenshot 2023-06-14 at 09 39 57

Building when these files are edited should be no different than the last master build.
Rational being no code changes should expect no test failures so it's just a waste of time and compute.

I've put together a demo repo with an [action](https://github.com/StephenFlavin/actions-demo/blob/main/.github/workflows/hello-world.yml#L4-L7) that configures
```yaml
  pull_request:
    paths-ignore:
      - '**.md'
      - '.i-am-a-hidden-file'
      - 'docs/**'
```
[Result](https://github.com/StephenFlavin/actions-demo/pulls): 
Screenshot 2023-06-14 at 09 44 24
so the only edit that caused a build wasn't in `paths-ignore`

**Comment by StephenFlavin** [comment]
p.s. I removed scripts from the PR because there could be scripts used to run builds like https://github.com/aws/aws-sdk-java-v2/blob/master/scripts/run-integ-test

**Comment by StephenFlavin** [comment]
I haven't added a changelog entry as it's not really any of `feature, bugfix, deprecation, removal, documentation`
move of a 🚧 "maintenance" 🚧 change

**Review by cenedhryn — APPROVED** [review]

**Review by cenedhryn — APPROVED** [review]

**Comment by debora-ito** [comment]
@StephenFlavin just a quick update: looks like it didn't work, successful codebuilds are still required - example: https://github.com/aws/aws-sdk-java-v2/pull/4276

Maybe there's some sort of precedence in the rules? Let me know if you have any thoughts.

**Comment by StephenFlavin** [comment]
Hi Deborah,
Yeah I'm not sure, afaict it should be skipped.
One thing I don't understand is if you look at the build for this pr there seems to be two sets of runners, the native GitHub ones and special Amazon ones
Screenshot_20230811-223147
Could this be something in a PR template or something?

**Comment by StephenFlavin** [comment]
It's possible that it's a branch protection rule from doing some reading but only repo admins will have access to check

**Pull request merged**
