### PR TITLE
Provide a clearer exception message when building a ReadBatch or WriteBatch without setting the mappedTableResource (table)

### PR DESCRIPTION
**Pull request by swar8080**
Currently, a NullPointerException is thrown if you forget to call the `WriteBatch` builder with `mappedTableResource(MappedTableResource<T>)`. `ReadBatch` has the same problem

## Motivation and Context

```
    DynamoDbEnhancedClient client ...
    DynamoDbTable<Customer> customerTable = client.table("customer-table", customerSchema);
    Customer customer = ...

    // This will fail with a NullPointerException, both for addPutItem* and addDeleteItem*
    client.batchWriteItem(builder -> builder.addWriteBatch(
        WriteBatch.builder(Customer.class)
            .addPutItem(customer)
            .build()
    ));

   // This works correctly
   client.batchWriteItem(builder -> builder.addWriteBatch(
        WriteBatch.builder(Customer.class)
            .mappedTableResource(customerTable)
            .addPutItem(customer)
            .build()
    ));
```

## Modifications
Add a clearer error message in the `NullPointerException` letting the person know they forgot to set a `mappedTableResource`

## Testing
Updated unit tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by debora-ito** [comment]
@swar8080 I understand the problem, but I don't think we should deprecate the current builder for this.
Do you think a better error message in case of a null mappedTableResource would be helpful?

**Comment by swar8080** [comment]
@debora-ito okay I just updated the `NullPointerException`'s message and got rid of the other changes

**Review by dagnir — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by dagnir** [comment]
@all-contributors please add @swar8080 for code

**Pull request merged**
