### PR TITLE
Updating versions to 2.0.0-preview-4-SNAPSHOT.

### PR DESCRIPTION
**Pull request by shorea**

### CODE REVIEW

**Comment by varunnvs92** [comment]
After the preview-3 is released, don't forget to merge master into "release" branch.

**Comment by shorea** [comment]
> "It might be a basic question. Why do we update to a snapshot version everytime?"

Not sure, I was just following orders from Kyle :). 

> "After the preview-3 is released, don't forget to merge master into "release" branch."

I can do that, is that for something in particular?

**Comment by kiiadi** [comment]
> It might be a basic question. Why do we update to a snapshot version every-time?

https://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it

**Comment by kiiadi** [comment]
> After the preview-3 is released, don't forget to merge master into "release" branch.

the version that gets merged to release should be exactly the same as the code-base that the release was run from (so version 2.0.0-preview-3)

**Comment by shorea** [comment]
Is that important for today or just in the future when we hang our CI off of the release branch?

**Comment by kiiadi** [comment]
> Is that important for today or just in the future when we hang our CI off of the release branch?

Which bit?

The `release` branch should echo the latest code that is released, so customers who don't want to look at the unreleased `master` but do want to look at the code can refer to the `release` branch. This should include the version number (because, as I say, it should match the codebase that the released artifacts in maven were created from).

In terms of `-SNAPSHOT` this is a fairly common practice in maven-land (even v1 does it : https://github.com/aws/aws-sdk-java/blob/master/pom.xml#L7). The `SNAPSHOT` bit tells the build system, hey this artifact might change, you might want to re-fetch it occasionally. Without `SNAPSHOT` at the end maven assumes that the artifact will never change.

**Pull request closed without merging**
