### PR TITLE
Updated AttributeMap to not close ExecutorService on Java 21

### PR DESCRIPTION
**Pull request by michaeldimchuk**
As of Java 21, [ExecutorService](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ExecutorService.html) extends `AutoCloseable`, so `AttributeMap#close` needs to be updated to avoid closing the executor and potentially cause a deadlock.

## Motivation and Context
Starting with Java 21, `ExecutorService` extends the `AutoCloseable` interface, which causes `AttributeMap#close` to pick up executor instances and try and close them, which can create deadlocks and cause the application to hang.

Issue: https://github.com/aws/aws-sdk-java-v2/issues/4395

## Modifications
Updated the `AttributeMap#close` method to first check if the attribute is an ExecutorService, and shut it down if so, otherwise check if the object is closeable and close it if needed.

## Testing
- Added a test case to ensure that ExecutorService instances are explicitly shut down and not closed
- Added a test case that running `AttributeMap#close` on a thread owned by an ExecutorService the `AttributeMap` instance manages does not result in a deadlock
- Ran all the tests to verify that the changes don't break anything, tested on an M1 MacBook Air with Java 17
- Validated that the new code does not introduce any new issues and maintains the same expected behavior as before

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by dagnir** [comment]
Thanks @michaeldimchuk, change looks good to me. Let me trigger our tests

**Comment by michaeldimchuk** [comment]
Not totally sure why all the jobs failed on the `Configure AWS Credentials` stage, only difference I see is that the `role-to-assume` property is missing from the action inputs (comparing to other builds that passed this stage), but I don't see how this set of changes could've removed that

**Comment by dagnir** [comment]
> Not totally sure why all the jobs failed on the Configure AWS Credentials stage, only difference I see is that the role-to-assume property is missing from the action inputs (comparing to other builds that passed this stage), but I don't see how this set of changes could've removed that

You're fine, this is expected behavior. Our CI setup doesn't allow auto builds for forked PRs (we have to manually trigger them).

**Comment by dagnir** [comment]
Integ test failure because of Maven connection reset. Retrying

**Review by dagnir — APPROVED** [review]

**Comment by dagnir** [comment]
LGTM, thanks!

**Comment by dagnir** [comment]
@all-contributors please add @michaeldimchuk for code

**Pull request merged**
