### PR TITLE
Update baseline data

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
- Update baseline result to the latest data
- Update `BenchmarkResultProcessor` to check difference percentage if the current data and baseline data are statistically different. 

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by dagnir** [comment]
Can we be a little more restrictive? Or is anything higher too strict as well?

**Comment by zoewangg** [comment]
> Can we be a little more restrictive? Or is anything higher too strict as well?

Going to test it out

**Comment by zoewangg** [comment]
The `compare` method turns out not very reliable. It's always showing statistically different even though the difference is only `21`.  Going to try to add a 10% margin

```
Baseline: apicall.httpclient.async.NettyHttpClientH1Benchmark.sequentialApiCall 1720.1013604261893

Result: apicall.httpclient.async.NettyHttpClientH1Benchmark.sequentialApiCall 1699.547
```

**Comment by zoewangg** [comment]
Benchmark  |  w/  HealthCheckedChannelPool | w/o HealthCheckedChannelPool |     
------------ | -------------  | -----------                              
NettyClientH1NonTlsBenchmark.concurrentApiCall  |  7313 | 8238
NettyClientH1NonTlsBenchmark.sequentialApiCall |  2192 | 2380
NettyHttpClientH1Benchmark.concurrentApiCall (jdk) |  6279 | 7113
NettyHttpClientH1Benchmark.sequentialApiCall (jdk) |  1699 |  1813
NettyHttpClientH2Benchmark.concurrentApiCall (jdk) | 4272 | 4545
NettyHttpClientH2Benchmark.sequentialApiCall (jdk) | 1605 | 1712

**Comment by dagnir** [comment]
Are these baseline numbers run with `HealthCheckedChannelPool` removed?

**Comment by zoewangg** [comment]
No, it's with current code base.  The change in #1191 has improved the performance (we didn't update the baseline after the change), and then the latency introduced in `HealthCheckedChannelPool` "reverted" the performance back to before.

**Pull request merged**
