### PR TITLE
Relocate DDB Mapper classes to a test module

### PR DESCRIPTION
**Pull request by dagnir**
All the mapper classes are now in test/dynamodbmapper-v1.

### CODE REVIEW

**Comment by spfink** [comment]
Have you verified the integration tests all pass?

**Comment by dagnir** [comment]
The results should be unchanged since the files were just shuffled around. I'll kick one off though just in case

**Comment by dagnir** [comment]
Confirmed integration tests are passing.

**Comment by spfink** [comment]
Could we not do something like

services/dynamodb/java
services/dynamodb/test
services/dynamodb/it
services/dynamodb/test-utils

test/dynamodbmapper-v1

**Comment by dagnir** [comment]
We can move the shared test classes into `src/main` but that would mean having non-test dependencies JUnit, etc in dynamodb. I like having the separate test-utils packages since it still allows the tests to remain as test scope.

**Comment by kiiadi** [comment]
@dagnir I agree, separate package is good.

**Comment by kiiadi** [comment]
But maybe we can stick the test utils in a deprecated package under the base test-utils package?

**Comment by dagnir** [comment]
@kiiadi Sounds reasonable. I'll do that

**Comment by dagnir** [comment]
@kiiadi Actually nevermind, that creates a cycle: `test-utils` -> `dynamodb` -> `test-utils`. `dynamodb` inherits the `test-utils` dependency from `services`

**Comment by dagnir** [comment]
Spoke offline with @kiiadi and decided to get rid of the `dynamodb-test-utils` package and just copy those files into `test/dynamodbmapper-v1`. Will merge the `dynamodb` and `dynamodb-tests` package back together and get rid of `dynamodb-parent`.

**Comment by dagnir** [comment]
@kiiadi Updated based on our discussion.

**Pull request merged**
