### PR TITLE
Invalid javascript header, not complaint with the embedded IANA reference

### PR DESCRIPTION
**Pull request by joeyvandijk**
As described in http://www.ietf.org/rfc/rfc4329.txt `application/x-javascript` was temporary but not final and therefore this should be changed, while (new) embedded (tv) browsers do support IANA standards, but could perhaps not-know/skip `application/x-javascript` support which will mean that Javascript will not be executed.

I do understand that many plugins depend on this reference (like the Jenkins S3 plugin), but this is invalid. Any input about use-cases that could be impacted?

Same issue with `v1` version: https://github.com/aws/aws-sdk-java/pull/1234

### CODE REVIEW

**Comment by shorea** [comment]
Interesting, this seems like a bigger bug since we don't appear to be using this file at all anymore. This might make sense to add in the new RequestBody class where we return octet stream when the content is sourced from an input stream/string/byte buffer, and for files we try to detect the actual content type using these mappings.

**Comment by joeyvandijk** [comment]
@shorea https://wiki.jenkins.io/display/JENKINS/S3+Plugin is using this file for example.

**Comment by shorea** [comment]
We exposed it in v1 and used it in the S3 client (https://github.com/aws/aws-sdk-java/blob/08207c0d96cd2e532d544a98c984545c77a2256f/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1615) but that functionality appears to be gone in V2. We also should move this resource to an S3 namespace so it's not in the root.

**Comment by kiiadi** [comment]
As @shorea said - this isn't currently used in v2 and we should implement something that does what v1 did in terms of setting the mime-type - i've opened a feature request to track this : https://github.com/aws/aws-sdk-java-v2/issues/357

For now I think we should probably remove this mime.type file since it's not used by the SDK at present and we *may* want to change the implementation when we do get to #357

**Pull request closed without merging**
