### PR TITLE
Add Endpoint & TlsContext to S3ClientConfiguration used by S3TransferManager

### PR DESCRIPTION
**Pull request by ron1**
## Motivation and Context

Resolves https://github.com/aws/aws-sdk-java-v2/issues/2945
Also resolves https://github.com/aws/aws-sdk-java-v2/issues/2740 and https://github.com/aws/aws-sdk-java-v2/issues/2896

## Description

Add Endpoint and TlsContext to S3ClientConfiguration used by S3TransferManager

## Testing

Tested locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by medjaoua** [comment]
Hello,

Can we have a date for validation of this pull request.
I have to add the endpoint in these classes and if done, it will be helpful a lot.

Thanks in advance.

Best Regards,

**Comment by zoewangg** [comment]
Apologies for the delayed response and thank you for your interest in contributing to our project. We are actually working on refactoring on the configuration of the transfer manager; we are planning to remove S3Configuration from the transfer manager builder and allow users to pass the S3AsyncClient directly where they can configure the endpoint and other settings directly. This way, you don't have to configure the same settings twice on the S3 client as well as the transfer manager.

We will close this PR for now. We appreciate your time and effort spent on this! :)

**Comment by ron1** [comment]
@zoewangg Do you know if the refactored S3TransferManager require a CRT-based S3AsyncClient?

**Comment by zoewangg** [comment]
@ron1 The current design is that S3TransferManager will create a CRT based S3AsyncClient by default, but users can pass an instance of S3AsyncClient to it, CRT based or Java based. Would this work for your use-case? Do you have any other feedback on the Transfer Manager?

**Comment by ron1** [comment]
@zoewangg Yes, enabling S3TransferManager to consume any S3AsyncClient instance, CRT-based or not, will work for us.

**Pull request closed without merging**
