### PR TITLE
remove obsolete build file (build.properties)

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
cc: @millems

**Comment by kiiadi** [comment]
Probably don't need the changelog for this - it's just housekeeping.

**Comment by sullis** [comment]
Please merge this :-)

**Comment by sullis** [comment]
Please merge this :-)

**Comment by sullis** [comment]
please merge :)

**Comment by millems** [comment]
Sorry about the delay! Could you squash this into one commit really quick?

**Comment by sullis** [comment]
@millems  Github Projects support "squash merging" 

https://github.com/blog/2141-squash-your-commits

Do you have squash merging enabled on this project?

**Comment by sullis** [comment]
per the Github blog:  "Only allow squash commits This is a new option which lets you force commit squashing on all pull requests merged via the merge button."

**Comment by millems** [comment]
We do rebased merges, and github unfortunately doesn't seem to support automatic squashing and rebasing. Just one or the other.

**Comment by sullis** [comment]
Ready for merge.

**Comment by millems** [comment]
Thank you!!

**Pull request merged**
